services:
  ollama:
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - './mounts/ollama:/root/.ollama'
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8181'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.3
    ports:
      - 8181:8181
      - 50051:50051
    volumes:
      - ./mounts/weviate:/var/lib/weaviate
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=ai-rag-demo
      - POSTGRES_USER=ai-rag-demo
      - POSTGRES_DB=ai-rag-demo