spring:
  application:
    name: ai-rag-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/ai-rag-demo
    username: ai-rag-demo
    password: ai-rag-demo
  ai:
    vectorstore:
      weaviate:
        host: localhost:8181
    ollama:
      init:
        pull-model-strategy: when_missing
        timeout: 1h
        max-retries: 1
        chat:
          additional-models:
            - llama3.1
          include: true
        embedding:
          additional-models:
            - llama3.1
          include: true
      chat:
        model: mistral
      embedding:
        model: mistral
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
    republish-outstanding-events-on-restart: true

management:
  endpoint:
    metrics:
      enabled: true
    modulith:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'