spring:
  application:
    name: ai-rag-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/ai-rag-demo
    username: ai-rag-demo
    password: ai-rag-demo
  ai:
    vectorstore:
      pgvector:
        dimensions: 1536
        distance-type: cosine_distance
        index-type: hnsw
    ollama:
      chat:
        model: llama3.1
      embedding:
        model: llama3.1